/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package POS.pnl;

import POS.banks.Dlg_banks;
import POS.bir_session.Dlg_x_reading;
import POS.cash_drawer.*;
import POS.category.Dlg_category;
import POS.customers.Dlg_customers;
import POS.discounts.Dlg_discounts;
import POS.expenses.Dlg_expenses;
import POS.items.Dlg_items;
import POS.main.Main;
import POS.new_inventory.Dlg_new_inventory;
import POS.purchase_order.Dlg_purchase_order;
import POS.receipts.Dlg_receipts;
import POS.reports.*;
import POS.sales.Dlg_sales;
import POS.services.Dlg_services;
import POS.stock_transfer.Dlg_rpt_stock_transfer;
import POS.stock_transfer.Dlg_stock_transfer;
import POS.suppliers.Dlg_supplier;
import POS.uom.Dlg_uom;
import POS.users.Dlg_login;
import POS.users.Dlg_users;
import POS.util.Alert;
import POS.util.Users;
import java.awt.*;
import java.beans.PropertyVetoException;
import javax.swing.*;
import mijzcx.synapse.desk.utils.Application;
import mijzcx.synapse.desk.utils.CloseDialog;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author i1
 */
public class Pnl_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Pnl_Dashboard
     */
    public Pnl_Dashboard() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        transactions = new javax.swing.JMenu();
        cb_t_sales = new javax.swing.JMenuItem();
        cb_t_receipts = new javax.swing.JMenuItem();
        cb_t_stock_tranfer = new javax.swing.JMenuItem();
        cb_t_inventory_adjuster = new javax.swing.JMenuItem();
        cb_t_purchase_order = new javax.swing.JMenuItem();
        cb_t_voider = new javax.swing.JMenuItem();
        maintenance = new javax.swing.JMenu();
        cb_m_items = new javax.swing.JMenuItem();
        cb_m_category = new javax.swing.JMenuItem();
        cb_m_users = new javax.swing.JMenuItem();
        cb_m_uom = new javax.swing.JMenuItem();
        cb_m_supplier = new javax.swing.JMenuItem();
        cb_m_customers = new javax.swing.JMenuItem();
        cb_m_discounts = new javax.swing.JMenuItem();
        cb_m_banks = new javax.swing.JMenuItem();
        cb_m_services = new javax.swing.JMenuItem();
        cb_m_expenses = new javax.swing.JMenuItem();
        reports = new javax.swing.JMenu();
        cb_r_sales = new javax.swing.JMenuItem();
        cb_r_sales_items = new javax.swing.JMenuItem();
        cb_r_cash_count = new javax.swing.JMenuItem();
        cb_r_receipts = new javax.swing.JMenuItem();
        cb_r_stock_transferred = new javax.swing.JMenuItem();
        cb_r_stocks_left_category = new javax.swing.JMenuItem();
        cb_r_stocks_left_supplier = new javax.swing.JMenuItem();
        cb_r_items = new javax.swing.JMenuItem();
        cb_r_purchase_order = new javax.swing.JMenuItem();
        cb_r_voider = new javax.swing.JMenuItem();
        bir = new javax.swing.JMenu();
        cb_b_x_reading = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        stand_by = new javax.swing.JMenuItem();
        LOGOUT = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JDesktopPane();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        lbl_business_name = new org.jdesktop.swingx.JXLabel();
        lbl_slogan = new org.jdesktop.swingx.JXLabel();

        jPopupMenu1.setBackground(new java.awt.Color(51, 153, 255));

        transactions.setBackground(new java.awt.Color(51, 153, 255));
        transactions.setForeground(new java.awt.Color(255, 255, 255));
        transactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N
        transactions.setText("TRANSACTIONS");
        transactions.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        transactions.setOpaque(true);
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });

        cb_t_sales.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_sales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_sales.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/sales.png"))); // NOI18N
        cb_t_sales.setText("SALES");
        cb_t_sales.setOpaque(true);
        cb_t_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_salesActionPerformed(evt);
            }
        });
        transactions.add(cb_t_sales);

        cb_t_receipts.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/receipts.png"))); // NOI18N
        cb_t_receipts.setText("RECEIPTS");
        cb_t_receipts.setOpaque(true);
        cb_t_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_receiptsActionPerformed(evt);
            }
        });
        transactions.add(cb_t_receipts);

        cb_t_stock_tranfer.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_stock_tranfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_stock_tranfer.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_stock_tranfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/stock_transfer.png"))); // NOI18N
        cb_t_stock_tranfer.setText("STOCK TRANSFER");
        cb_t_stock_tranfer.setOpaque(true);
        cb_t_stock_tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_stock_tranferActionPerformed(evt);
            }
        });
        transactions.add(cb_t_stock_tranfer);

        cb_t_inventory_adjuster.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_inventory_adjuster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_inventory_adjuster.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_inventory_adjuster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/items.png"))); // NOI18N
        cb_t_inventory_adjuster.setText("INVENTORY ADJUSTER");
        cb_t_inventory_adjuster.setOpaque(true);
        cb_t_inventory_adjuster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_inventory_adjusterActionPerformed(evt);
            }
        });
        transactions.add(cb_t_inventory_adjuster);

        cb_t_purchase_order.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_purchase_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_purchase_order.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_purchase_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_t_purchase_order.setText("PURCHASE ORDER");
        cb_t_purchase_order.setOpaque(true);
        cb_t_purchase_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_purchase_orderActionPerformed(evt);
            }
        });
        transactions.add(cb_t_purchase_order);

        cb_t_voider.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_voider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_voider.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_voider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_drop.png"))); // NOI18N
        cb_t_voider.setText("VOIDER");
        cb_t_voider.setOpaque(true);
        cb_t_voider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_voiderActionPerformed(evt);
            }
        });
        transactions.add(cb_t_voider);

        jPopupMenu1.add(transactions);

        maintenance.setBackground(new java.awt.Color(51, 153, 255));
        maintenance.setForeground(new java.awt.Color(255, 255, 255));
        maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/security_manager.png"))); // NOI18N
        maintenance.setText("MAINTENANCE");
        maintenance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        maintenance.setOpaque(true);

        cb_m_items.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/items.png"))); // NOI18N
        cb_m_items.setText("ITEM");
        cb_m_items.setOpaque(true);
        cb_m_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_itemsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_items);

        cb_m_category.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_category.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/category.png"))); // NOI18N
        cb_m_category.setText("CATEGORY");
        cb_m_category.setOpaque(true);
        cb_m_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_categoryActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_category);

        cb_m_users.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_users.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_users.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/users.png"))); // NOI18N
        cb_m_users.setText("USERS");
        cb_m_users.setOpaque(true);
        cb_m_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_usersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_users);

        cb_m_uom.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_uom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_uom.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_uom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/uom.png"))); // NOI18N
        cb_m_uom.setText("UNIT OF MEASURE");
        cb_m_uom.setOpaque(true);
        cb_m_uom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_uomActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_uom);

        cb_m_supplier.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_supplier.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/suppliers.png"))); // NOI18N
        cb_m_supplier.setText("SUPPLIER");
        cb_m_supplier.setOpaque(true);
        cb_m_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_supplierActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_supplier);

        cb_m_customers.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_customers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_customers.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer.png"))); // NOI18N
        cb_m_customers.setText("CUSTOMERS");
        cb_m_customers.setOpaque(true);
        cb_m_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_customersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_customers);

        cb_m_discounts.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_discounts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_discounts.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_discounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer_item_pricing.png"))); // NOI18N
        cb_m_discounts.setText("DISCOUNTS");
        cb_m_discounts.setOpaque(true);
        cb_m_discounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_discountsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_discounts);

        cb_m_banks.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_banks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_banks.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_banks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_b.png"))); // NOI18N
        cb_m_banks.setText("BANKS");
        cb_m_banks.setOpaque(true);
        cb_m_banks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_banksActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_banks);

        cb_m_services.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_services.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_services.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N
        cb_m_services.setText("SERVICES");
        cb_m_services.setOpaque(true);
        cb_m_services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_servicesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_services);

        cb_m_expenses.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_expenses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_expenses.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_m_expenses.setText("EXPENSES");
        cb_m_expenses.setOpaque(true);
        cb_m_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_expensesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_expenses);

        jPopupMenu1.add(maintenance);

        reports.setBackground(new java.awt.Color(51, 153, 255));
        reports.setForeground(new java.awt.Color(255, 255, 255));
        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        reports.setText("REPORTS");
        reports.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reports.setOpaque(true);

        cb_r_sales.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_sales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_sales.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales.png"))); // NOI18N
        cb_r_sales.setText("SALES REPORT");
        cb_r_sales.setOpaque(true);
        cb_r_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_salesActionPerformed(evt);
            }
        });
        reports.add(cb_r_sales);

        cb_r_sales_items.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_sales_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_sales_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_sales_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_ledger.png"))); // NOI18N
        cb_r_sales_items.setText("SALES ITEMS");
        cb_r_sales_items.setOpaque(true);
        cb_r_sales_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_sales_itemsActionPerformed(evt);
            }
        });
        reports.add(cb_r_sales_items);

        cb_r_cash_count.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_cash_count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_cash_count.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_cash_count.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_b.png"))); // NOI18N
        cb_r_cash_count.setText("CASH COUNT");
        cb_r_cash_count.setOpaque(true);
        cb_r_cash_count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_cash_countActionPerformed(evt);
            }
        });
        reports.add(cb_r_cash_count);

        cb_r_receipts.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/receipts.png"))); // NOI18N
        cb_r_receipts.setText("RECEIPTS");
        cb_r_receipts.setOpaque(true);
        cb_r_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_receiptsActionPerformed(evt);
            }
        });
        reports.add(cb_r_receipts);

        cb_r_stock_transferred.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stock_transferred.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stock_transferred.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stock_transferred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/orders_and_deliveries.png"))); // NOI18N
        cb_r_stock_transferred.setText("STOCK TRANSFER");
        cb_r_stock_transferred.setOpaque(true);
        cb_r_stock_transferred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stock_transferredActionPerformed(evt);
            }
        });
        reports.add(cb_r_stock_transferred);

        cb_r_stocks_left_category.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stocks_left_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stocks_left_category.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stocks_left_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stocks_left_category.setText("STOCKS LEFT by Category");
        cb_r_stocks_left_category.setOpaque(true);
        cb_r_stocks_left_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stocks_left_categoryActionPerformed(evt);
            }
        });
        reports.add(cb_r_stocks_left_category);

        cb_r_stocks_left_supplier.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stocks_left_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stocks_left_supplier.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stocks_left_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stocks_left_supplier.setText("STOCKS LEFT by Supplier");
        cb_r_stocks_left_supplier.setOpaque(true);
        cb_r_stocks_left_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stocks_left_supplierActionPerformed(evt);
            }
        });
        reports.add(cb_r_stocks_left_supplier);

        cb_r_items.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_items.setText("ITEMS by Category");
        cb_r_items.setOpaque(true);
        cb_r_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_itemsActionPerformed(evt);
            }
        });
        reports.add(cb_r_items);

        cb_r_purchase_order.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_purchase_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_purchase_order.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_purchase_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_r_purchase_order.setText("PURCHASE ORDER");
        cb_r_purchase_order.setOpaque(true);
        cb_r_purchase_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_purchase_orderActionPerformed(evt);
            }
        });
        reports.add(cb_r_purchase_order);

        cb_r_voider.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_voider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_voider.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_voider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_drop.png"))); // NOI18N
        cb_r_voider.setText("VOIDER");
        cb_r_voider.setOpaque(true);
        cb_r_voider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_voiderActionPerformed(evt);
            }
        });
        reports.add(cb_r_voider);

        jPopupMenu1.add(reports);

        bir.setBackground(new java.awt.Color(51, 153, 255));
        bir.setForeground(new java.awt.Color(255, 255, 255));
        bir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/reports.PNG"))); // NOI18N
        bir.setText("BIR");
        bir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bir.setOpaque(true);

        cb_b_x_reading.setBackground(new java.awt.Color(51, 153, 255));
        cb_b_x_reading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_x_reading.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_x_reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_b_x_reading.setText("Z Reading");
        cb_b_x_reading.setOpaque(true);
        cb_b_x_reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_x_readingActionPerformed(evt);
            }
        });
        bir.add(cb_b_x_reading);

        jPopupMenu1.add(bir);

        help.setBackground(new java.awt.Color(51, 153, 255));
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/help.png"))); // NOI18N
        help.setText("HELP");
        help.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        help.setOpaque(true);
        jPopupMenu1.add(help);

        stand_by.setBackground(new java.awt.Color(51, 153, 255));
        stand_by.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stand_by.setForeground(new java.awt.Color(255, 255, 255));
        stand_by.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/maintenance.png"))); // NOI18N
        stand_by.setText("STAND BY");
        stand_by.setOpaque(true);
        stand_by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stand_byActionPerformed(evt);
            }
        });
        jPopupMenu1.add(stand_by);

        LOGOUT.setBackground(new java.awt.Color(51, 153, 255));
        LOGOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/s_reload.png"))); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.setOpaque(true);
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jPopupMenu1.add(LOGOUT);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Point of Sale");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(248, 248, 248)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(209, 209, 194));

        jXPanel2.setAlpha(0.5F);
        jXPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jXPanel2.setOpaque(true);

        lbl_business_name.setForeground(new java.awt.Color(1, 33, 54));
        lbl_business_name.setText("SYNAPSE SOFTWARE TECHNOLOGY");
        lbl_business_name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lbl_slogan.setForeground(new java.awt.Color(1, 33, 54));
        lbl_slogan.setText("INTEGRATING BUSINESS THROUGH TECHNOLOGY");
        lbl_slogan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jXPanel2Layout = new javax.swing.GroupLayout(jXPanel2);
        jXPanel2.setLayout(jXPanel2Layout);
        jXPanel2Layout.setHorizontalGroup(
            jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_slogan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_business_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)))
        );
        jXPanel2Layout.setVerticalGroup(
            jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_business_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_slogan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jXPanel2);
        jXPanel2.setBounds(0, 320, 870, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        hover(jLabel3);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        exit(jLabel3);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        hover2(jLabel7);
        pm_tbl_users();
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        exit2(jLabel7);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    }//GEN-LAST:event_jLabel7MouseClicked

    private void cb_m_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_categoryActionPerformed
        category();
    }//GEN-LAST:event_cb_m_categoryActionPerformed

    private void cb_m_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_usersActionPerformed
        users();
    }//GEN-LAST:event_cb_m_usersActionPerformed

    private void cb_m_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_itemsActionPerformed
        items();
    }//GEN-LAST:event_cb_m_itemsActionPerformed

    private void cb_t_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_salesActionPerformed
        sales();
    }//GEN-LAST:event_cb_t_salesActionPerformed

    private void cb_r_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_salesActionPerformed
        sales_report();
    }//GEN-LAST:event_cb_r_salesActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        cashout();
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void cb_t_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_receiptsActionPerformed
        // TODO add your handling code here:
        receipts();
    }//GEN-LAST:event_cb_t_receiptsActionPerformed

    private void cb_t_stock_tranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_stock_tranferActionPerformed
        // TODO add your handling code here:
        stock_transfer();
    }//GEN-LAST:event_cb_t_stock_tranferActionPerformed

    private void cb_m_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_supplierActionPerformed
        supplier();
    }//GEN-LAST:event_cb_m_supplierActionPerformed

    private void cb_r_cash_countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_cash_countActionPerformed
        rpt_cash_drawer();
    }//GEN-LAST:event_cb_r_cash_countActionPerformed

    private void cb_r_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_receiptsActionPerformed
        // TODO add your handling code here:
        rpt_receipts();
    }//GEN-LAST:event_cb_r_receiptsActionPerformed

    private void cb_r_stock_transferredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stock_transferredActionPerformed
        // TODO add your handling code here:
        rpt_stock_transfer();
    }//GEN-LAST:event_cb_r_stock_transferredActionPerformed

    private void cb_r_stocks_left_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stocks_left_categoryActionPerformed
        rpt_stock_left_category();
    }//GEN-LAST:event_cb_r_stocks_left_categoryActionPerformed

    private void stand_byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stand_byActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_stand_byActionPerformed

    private void cb_r_sales_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_sales_itemsActionPerformed
        // TODO add your handling code here:
        sales_items();
    }//GEN-LAST:event_cb_r_sales_itemsActionPerformed

    private void cb_m_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_customersActionPerformed
        m_customers();
    }//GEN-LAST:event_cb_m_customersActionPerformed

    private void cb_m_discountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_discountsActionPerformed
        // TODO add your handling code here:
        m_discount();
    }//GEN-LAST:event_cb_m_discountsActionPerformed

    private void cb_m_uomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_uomActionPerformed
        m_uom();
    }//GEN-LAST:event_cb_m_uomActionPerformed

    private void cb_m_banksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_banksActionPerformed
        // TODO add your handling code here:
        m_banks();
    }//GEN-LAST:event_cb_m_banksActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cashout();
    }//GEN-LAST:event_formWindowClosing

    private void cb_r_stocks_left_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stocks_left_supplierActionPerformed
        // TODO add your handling code here:
        rpt_stock_left_supplier();
    }//GEN-LAST:event_cb_r_stocks_left_supplierActionPerformed

    private void cb_r_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_itemsActionPerformed
        // TODO add your handling code here:
        rpt_items_category();
    }//GEN-LAST:event_cb_r_itemsActionPerformed

    private void cb_t_inventory_adjusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_inventory_adjusterActionPerformed
        // TODO add your handling code here:
        adjust_inventory();
    }//GEN-LAST:event_cb_t_inventory_adjusterActionPerformed

    private void cb_b_x_readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_x_readingActionPerformed
        // TODO add your handling code here:
        z_reading();
    }//GEN-LAST:event_cb_b_x_readingActionPerformed

    private void cb_m_servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_servicesActionPerformed
        // TODO add your handling code here:
        m_services();
    }//GEN-LAST:event_cb_m_servicesActionPerformed

    private void cb_m_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_expensesActionPerformed
        // TODO add your handling code here:
        m_expenses();
    }//GEN-LAST:event_cb_m_expensesActionPerformed

    private void cb_t_purchase_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_purchase_orderActionPerformed
        // TODO add your handling code here:
        t_purchase_order();
    }//GEN-LAST:event_cb_t_purchase_orderActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        // TODO add your handling code here:
        t_purchase_order();
    }//GEN-LAST:event_transactionsActionPerformed

    private void cb_r_purchase_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_purchase_orderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_r_purchase_orderActionPerformed

    private void cb_t_voiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_voiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_t_voiderActionPerformed

    private void cb_r_voiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_voiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_r_voiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Application.setSystemLookAndFeel();
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
//                new Pnl_Dashboard().setVisible(true);
                Pnl_Dashboard aw = new Pnl_Dashboard();
                String url = "/POS/img/5.png";
//                Wallpaper.do_set(url, aw.jPanel1);

                Toolkit tk = Toolkit.getDefaultToolkit();
                int xSize = ((int) tk.getScreenSize().
                        getWidth());
                int ySize = ((int) tk.getScreenSize().
                        getHeight());
                aw.setSize(xSize, ySize);
                Dimension d = aw.jPanel1.getSize();
                Dimension d2 = aw.jXPanel2.getSize();
                aw.jXPanel2.setSize(xSize, d2.height);
                aw.jXPanel2.updateUI();
                aw.setVisible(true);
                aw.login();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LOGOUT;
    private javax.swing.JMenu bir;
    private javax.swing.JMenuItem cb_b_x_reading;
    private javax.swing.JMenuItem cb_m_banks;
    private javax.swing.JMenuItem cb_m_category;
    private javax.swing.JMenuItem cb_m_customers;
    private javax.swing.JMenuItem cb_m_discounts;
    private javax.swing.JMenuItem cb_m_expenses;
    private javax.swing.JMenuItem cb_m_items;
    private javax.swing.JMenuItem cb_m_services;
    private javax.swing.JMenuItem cb_m_supplier;
    private javax.swing.JMenuItem cb_m_uom;
    private javax.swing.JMenuItem cb_m_users;
    private javax.swing.JMenuItem cb_r_cash_count;
    private javax.swing.JMenuItem cb_r_items;
    private javax.swing.JMenuItem cb_r_purchase_order;
    private javax.swing.JMenuItem cb_r_receipts;
    private javax.swing.JMenuItem cb_r_sales;
    private javax.swing.JMenuItem cb_r_sales_items;
    private javax.swing.JMenuItem cb_r_stock_transferred;
    private javax.swing.JMenuItem cb_r_stocks_left_category;
    private javax.swing.JMenuItem cb_r_stocks_left_supplier;
    private javax.swing.JMenuItem cb_r_voider;
    private javax.swing.JMenuItem cb_t_inventory_adjuster;
    private javax.swing.JMenuItem cb_t_purchase_order;
    private javax.swing.JMenuItem cb_t_receipts;
    private javax.swing.JMenuItem cb_t_sales;
    private javax.swing.JMenuItem cb_t_stock_tranfer;
    private javax.swing.JMenuItem cb_t_voider;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JDesktopPane jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXLabel lbl_business_name;
    private org.jdesktop.swingx.JXLabel lbl_slogan;
    private javax.swing.JMenu maintenance;
    private javax.swing.JMenu reports;
    private javax.swing.JMenuItem stand_by;
    private javax.swing.JMenu transactions;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        Main.MyDB.setNames("db_fortune_three");
        String business_name = System.getProperty("business_name", "SYNAPSE SOFTWARE TECHNOLOGY");
        String slogan = System.getProperty("slogan", "INTEGRATING BUSINESS THROUGH TECHNOLOGY");
//        jPanel1.setLayout(new BorderLayout());
        lbl_business_name.setText(business_name);
        lbl_slogan.setText(slogan);
//        jPanel1.setUI(new DesktopPaneUI() {


//        });
    }

    public JDesktopPane pane() {
        return jPanel1;
    }

    public JXPanel pane2() {
        return jXPanel2;
    }

    public void login() {
        Window p = (Window) this;
        Dlg_login nd = Dlg_login.create(p, true);
        nd.setTitle("");
        nd.setCallback(new Dlg_login.Callback() {

            @Override
            public void ok(CloseDialog closeDialog, Dlg_login.OutputData data) {
                closeDialog.ok();
                jPanel1.removeAll();
                jPanel1.removeAll();

                Dimension d = jPanel1.getSize();
                Dimension d2 = jXPanel2.getSize();
                jXPanel2.setSize(d.width, d2.height);
                jPanel1.add(jXPanel2);
                String url = "/POS/img/5.png";
//                Wallpaper.do_set(url, jPanel1);
                jPanel1.updateUI();
                set_account();
                if (Users.user_level == 1 && Users.t_sales.equals("1")) {
                    sales();
                }
            }
        });
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().
                getWidth());

        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - nd.getWidth()) / 2;
        final int y = (screenSize.height - nd.getHeight()) / 2;
        nd.setLocation(0, y);
        nd.setSize(xSize, 50);
        nd.setVisible(true);
    }

    private void set_account() {

        if (Users.t_sales.equals("0")) {
            cb_t_sales.setVisible(false);
        } else {
            cb_t_sales.setVisible(true);
        }

        if (Users.t_receipts.equals("0")) {
            cb_t_receipts.setVisible(false);
        } else {
            cb_t_receipts.setVisible(true);
        }

        if (Users.t_stock_transfer.equals("0")) {

            cb_t_stock_tranfer.setVisible(false);
        } else {
            cb_t_stock_tranfer.setVisible(true);
        }

        if (Users.m_items.equals("0")) {

            cb_m_items.setVisible(false);
        } else {
            cb_m_items.setVisible(true);
        }

        if (Users.m_category.equals("0")) {

            cb_m_category.setVisible(false);
        } else {
            cb_m_category.setVisible(true);
        }

        if (Users.m_users.equals("0")) {

            cb_m_users.setVisible(false);
        } else {
            cb_m_users.setVisible(true);
        }

        if (Users.m_uom.equals("0")) {

            cb_m_uom.setVisible(false);
        } else {
            cb_m_uom.setVisible(true);
        }

        if (Users.m_suppliers.equals("0")) {

            cb_m_supplier.setVisible(false);
        } else {
            cb_m_supplier.setVisible(true);
        }

        if (Users.r_sales.equals("0")) {

            cb_r_sales.setVisible(false);
        } else {
            cb_r_sales.setVisible(true);
        }

        if (Users.r_cash_count.equals("0")) {

            cb_r_cash_count.setVisible(false);
        } else {
            cb_r_cash_count.setVisible(true);
        }

        if (Users.r_receipts.equals("0")) {

            cb_r_receipts.setVisible(false);
        } else {
            cb_r_receipts.setVisible(true);
        }

        if (Users.r_stock_transferred.equals("0")) {

            cb_r_stock_transferred.setVisible(false);
        } else {
            cb_r_stock_transferred.setVisible(true);
        }

        if (Users.r_stock_take.equals("0")) {
            cb_r_stocks_left_category.setVisible(false);
        } else {
            cb_r_stocks_left_category.setVisible(true);
        }

        if (Users.m_customers.equals("0")) {
            cb_m_customers.setVisible(false);
        } else {
            cb_m_customers.setVisible(true);
        }
        if (Users.m_discount.equals("0")) {
            cb_m_discounts.setVisible(false);
        } else {
            cb_m_discounts.setVisible(true);
        }
        if (Users.m_banks.equals("0")) {
            cb_m_banks.setVisible(false);
        } else {
            cb_m_banks.setVisible(true);
        }
        if (Users.r_stock_left_supplier.equals("0")) {
            cb_r_stocks_left_supplier.setVisible(false);
        } else {
            cb_r_stocks_left_supplier.setVisible(true);
        }
        if (Users.t_inventory_adjuster.equals("0")) {
            cb_t_inventory_adjuster.setVisible(false);
        } else {
            cb_t_inventory_adjuster.setVisible(true);
        }
    }

    private void hover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(230, 227, 227));
        lbl.setForeground(new java.awt.Color(0, 0, 0));
    }

    private void exit(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(255, 255, 255));
        lbl.setForeground(new java.awt.Color(153, 153, 153));
    }

    private void hover2(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(29, 141, 253));
//        lbl.setForeground(new java.awt.Color(0, 0, 0));
    }

    private void exit2(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(51, 153, 255));
//        lbl.setForeground(new java.awt.Color(51, 153, 255));
    }

    private void pm_tbl_users() {

        Point l = jLabel7.getLocation();
        jPopupMenu1.show(this, l.x, l.y + 34);
    }

    private void users() {
        Dlg_users dtc = new Dlg_users();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("USERS", true, true, true, true);

        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (PropertyVetoException e) {
        }
//        jPanel1.setLayout(new BorderLayout());
    }

    private void items() {
        Dlg_items dtc = new Dlg_items();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("ITEMS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void category() {
        Dlg_category dtc = new Dlg_category();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("CATEGORY", true, true, true, true);

        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void sales() {
        final Dlg_sales dtc = new Dlg_sales();
        Dimension d2 = jPanel1.getSize();
        Dimension d = dtc.getSize();
        int width = d2.width;
        int height = d2.height;
        final JInternalFrame p22 = new JInternalFrame("SALES", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        p22.getRootPane().
                setWindowDecorationStyle(JRootPane.NONE);
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void sales_report() {
        Dlg_report_all_sales dtc = new Dlg_report_all_sales();
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("SALES REPORT", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
//        jPanel1.setLayout(new BorderLayout());
    }

    private void cashout() {
        if (Users.user_level == 0) {
            System.exit(1);
        } else {

            if (Users.is_active == 0) {

                Window p = (Window) this;
                Dlg_cash_out nd = Dlg_cash_out.create(p, true);
                nd.setTitle("");
                nd.do_pass_in(Users.checks, Users.drawer);
                nd.setCallback(new Dlg_cash_out.Callback() {

                    @Override
                    public void ok(CloseDialog closeDialog, Dlg_cash_out.OutputData data) {
                        closeDialog.ok();
                        S1_cash_drawer.edit_cash_drawer(data.drawer);
                        S1_cash_drawer_checks.add_cash_drawer_checks(data.drawer.checks);
                        S1_cash_drawer_expenses.add_cash_drawer_checks(data.drawer.exp);
                        Alert.set(0, "THANK YOU, HAVE A NICE DAY");
                        System.exit(1);
//                    login`
                    }
                });

                nd.setLocationRelativeTo(this);
                nd.setVisible(true);
            }
            if (Users.is_active == 1) {
//                JOptionPane.showMessageDialog(null, "adadad");
                Window p = (Window) this;
                Dlg_cash_out nd = Dlg_cash_out.create(p, true);
                nd.setTitle("");
                nd.do_pass(Users.checks, Users.drawer);
                nd.setCallback(new Dlg_cash_out.Callback() {

                    @Override
                    public void ok(CloseDialog closeDialog, Dlg_cash_out.OutputData data) {
                        closeDialog.ok();
                        S1_cash_drawer.edit_cash_drawer(data.drawer);
                        Alert.set(0, "THANK YOU, HAVE A NICE DAY");
                        System.exit(1);
//                    login`
                    }
                });
                nd.setLocationRelativeTo(this);
                nd.setVisible(true);
            }

        }
    }

    private void receipts() {
        Dlg_receipts dtc = new Dlg_receipts();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("RECEIPTS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void sales_items() {
        Dlg_sales_by_item dtc = new Dlg_sales_by_item();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("SALES ITEMS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void stock_transfer() {
        Dlg_stock_transfer dtc = new Dlg_stock_transfer();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("STOCK TRANSFER", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void supplier() {
        Dlg_supplier dtc = new Dlg_supplier();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("SUPPLIER", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void rpt_cash_drawer() {
        Dlg_rpt_cashdrawer dtc = new Dlg_rpt_cashdrawer();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("CASH COUNT", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void rpt_receipts() {
        Dlg_report_receipts dtc = new Dlg_report_receipts();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("RECEIPTS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void rpt_stock_transfer() {
        Dlg_rpt_stock_transfer dtc = new Dlg_rpt_stock_transfer();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("STOCK TRANSFER", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void rpt_stock_left_category() {
        Dlg_report_stock_left_category dtc = new Dlg_report_stock_left_category();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("STOCK LEFT by Category", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void rpt_stock_left_supplier() {
        Dlg_report_stock_left_supplier dtc = new Dlg_report_stock_left_supplier();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("STOCK LEFT by Supplier", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void rpt_items_category() {
        Dlg_report_items_by_category dtc = new Dlg_report_items_by_category();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("ITEMS by Category", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void m_customers() {
        Dlg_customers dtc = new Dlg_customers();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("CUSTOMERS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void m_discount() {
        Dlg_discounts dtc = new Dlg_discounts();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("DISCOUNTS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void m_uom() {
        Dlg_uom dtc = new Dlg_uom();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("UNIT OF MEASURE", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void m_banks() {
        Dlg_banks dtc = new Dlg_banks();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("BANKS", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void adjust_inventory() {
        Dlg_new_inventory dtc = new Dlg_new_inventory();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("INVENTORY ADJUSTER", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (PropertyVetoException e) {
        }
    }

    private void z_reading() {
        Dlg_x_reading dtc = new Dlg_x_reading();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("X READING", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void t_purchase_order() {
        Dlg_purchase_order dtc = new Dlg_purchase_order();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = jPanel1.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("Purchase Order", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width, height);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void m_services() {
        Dlg_services dtc = new Dlg_services();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("SERVICES", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }

    private void m_expenses() {
        Dlg_expenses dtc = new Dlg_expenses();
//        dtc.setModal(Modal.);
        dtc.do_pass();
        Dimension d = dtc.getSize();
        int width = d.width;
        int height = d.height;
        final JInternalFrame p22 = new JInternalFrame("EXPENSES", true, true, true, true);
        p22.add(dtc.getSurface());
        p22.setSize(width + 10, height + 20);
        p22.setFrameIcon(new javax.swing.ImageIcon(getClass().
                getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        try {
            if (p22.isVisible()) {
                jPanel1.remove(p22);
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.moveToFront();
                p22.setSelected(true);
                p22.show();
                jPanel1.repaint();
            } else {
                jPanel1.add(p22);
                p22.setLocation(jPanel1.getWidth() / 2 - p22.getWidth() / 2, jPanel1.
                        getHeight() / 2 - p22.getHeight() / 2);
                p22.show();
            }
        } catch (Exception e) {
        }
    }
}
