/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Retail.pnl;

import POS.users.Dlg_login;
import POS.users.MyUser;
import POS.users.User_previleges;
import POS.util.Alert;
import POS.util.DateType;

import POS.util.Focus_Fire;
import POS.util.Users;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import mijzcx.synapse.desk.utils.Application;
import mijzcx.synapse.desk.utils.CloseDialog;
import synsoftech.fields.Button;
import synsoftech.fields.Field;

/**
 *
 * @author i1
 */

public class Dashboard extends javax.swing.JFrame {
    /**
     * Creates new form Pnl_Dashboard
     */
    public Dashboard() {
        initComponents();
        myInit();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        transactions = new javax.swing.JMenu();
        cb_t_encode_inventory = new javax.swing.JMenuItem();
        cb_t_finalize_inventory = new javax.swing.JMenuItem();
        cb_t_salesman = new javax.swing.JMenuItem();
        cb_t_sales = new javax.swing.JMenuItem();
        cb_t_receipts = new javax.swing.JMenuItem();
        cb_t_finalize_receipts = new javax.swing.JMenuItem();
        cb_t_stock_tranfer = new javax.swing.JMenuItem();
        cb_t_inventory_adjuster = new javax.swing.JMenuItem();
        cb_t_purchase_order = new javax.swing.JMenuItem();
        cb_t_voider = new javax.swing.JMenuItem();
        cb_t_ar = new javax.swing.JMenuItem();
        cb_t_ar_encoding = new javax.swing.JMenuItem();
        cb_t_ap = new javax.swing.JMenuItem();
        cb_t_services = new javax.swing.JMenuItem();
        maintenance = new javax.swing.JMenu();
        cb_m_items = new javax.swing.JMenuItem();
        cb_m_category = new javax.swing.JMenuItem();
        cb_m_users = new javax.swing.JMenuItem();
        cb_m_uom = new javax.swing.JMenuItem();
        cb_m_supplier = new javax.swing.JMenuItem();
        cb_m_customers = new javax.swing.JMenuItem();
        cb_m_discounts = new javax.swing.JMenuItem();
        cb_m_banks = new javax.swing.JMenuItem();
        cb_m_services = new javax.swing.JMenuItem();
        cb_m_expenses = new javax.swing.JMenuItem();
        reports = new javax.swing.JMenu();
        cb_r_encoding_inventory = new javax.swing.JMenuItem();
        cb_r_sales = new javax.swing.JMenuItem();
        cb_r_sales_items = new javax.swing.JMenuItem();
        cb_r_cash_count = new javax.swing.JMenuItem();
        cb_r_receipts = new javax.swing.JMenuItem();
        cb_r_stock_transferred = new javax.swing.JMenuItem();
        cb_r_stocks_left_category = new javax.swing.JMenuItem();
        cb_r_stocks_left_supplier = new javax.swing.JMenuItem();
        cb_r_items = new javax.swing.JMenuItem();
        cb_r_purchase_order = new javax.swing.JMenuItem();
        cb_r_voider = new javax.swing.JMenuItem();
        cb_r_stock_status = new javax.swing.JMenuItem();
        cb_r_stock_ledger = new javax.swing.JMenuItem();
        cb_r_customers = new javax.swing.JMenuItem();
        bir = new javax.swing.JMenu();
        cb_b_x_reading = new javax.swing.JMenuItem();
        cb_b_z_reading = new javax.swing.JMenuItem();
        cb_b_reading_trails = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        stand_by = new javax.swing.JMenuItem();
        LOGOUT = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnl_main_holder = new javax.swing.JPanel();
        pnl_login = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_username = new Field.Input();
        jLabel12 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new Button.Default();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();

        jPopupMenu1.setBackground(new java.awt.Color(51, 153, 255));

        transactions.setBackground(new java.awt.Color(51, 153, 255));
        transactions.setForeground(new java.awt.Color(255, 255, 255));
        transactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N
        transactions.setText("TRANSACTIONS");
        transactions.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        transactions.setOpaque(true);
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });

        cb_t_encode_inventory.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_encode_inventory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_encode_inventory.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_encode_inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/branch.png"))); // NOI18N
        cb_t_encode_inventory.setText("ENCODING");
        cb_t_encode_inventory.setOpaque(true);
        cb_t_encode_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_encode_inventoryActionPerformed(evt);
            }
        });
        transactions.add(cb_t_encode_inventory);

        cb_t_finalize_inventory.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_finalize_inventory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_finalize_inventory.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_finalize_inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item.png"))); // NOI18N
        cb_t_finalize_inventory.setText("FINALIZE ENCODING");
        cb_t_finalize_inventory.setOpaque(true);
        cb_t_finalize_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_finalize_inventoryActionPerformed(evt);
            }
        });
        transactions.add(cb_t_finalize_inventory);

        cb_t_salesman.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_salesman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_salesman.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_salesman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_supplier.png"))); // NOI18N
        cb_t_salesman.setText("SALESMAN");
        cb_t_salesman.setOpaque(true);
        cb_t_salesman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_salesmanActionPerformed(evt);
            }
        });
        transactions.add(cb_t_salesman);

        cb_t_sales.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_sales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_sales.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/sales.png"))); // NOI18N
        cb_t_sales.setText("CASHIER");
        cb_t_sales.setOpaque(true);
        cb_t_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_salesActionPerformed(evt);
            }
        });
        transactions.add(cb_t_sales);

        cb_t_receipts.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/receipts.png"))); // NOI18N
        cb_t_receipts.setText("RECEIPTS");
        cb_t_receipts.setOpaque(true);
        cb_t_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_receiptsActionPerformed(evt);
            }
        });
        transactions.add(cb_t_receipts);

        cb_t_finalize_receipts.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_finalize_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_finalize_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_finalize_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/receipts.png"))); // NOI18N
        cb_t_finalize_receipts.setText("FINALIZE RECEIPTS");
        cb_t_finalize_receipts.setOpaque(true);
        cb_t_finalize_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_finalize_receiptsActionPerformed(evt);
            }
        });
        transactions.add(cb_t_finalize_receipts);

        cb_t_stock_tranfer.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_stock_tranfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_stock_tranfer.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_stock_tranfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/stock_transfer.png"))); // NOI18N
        cb_t_stock_tranfer.setText("STOCK TRANSFER");
        cb_t_stock_tranfer.setOpaque(true);
        cb_t_stock_tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_stock_tranferActionPerformed(evt);
            }
        });
        transactions.add(cb_t_stock_tranfer);

        cb_t_inventory_adjuster.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_inventory_adjuster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_inventory_adjuster.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_inventory_adjuster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/items.png"))); // NOI18N
        cb_t_inventory_adjuster.setText("INVENTORY ADJUSTER");
        cb_t_inventory_adjuster.setOpaque(true);
        cb_t_inventory_adjuster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_inventory_adjusterActionPerformed(evt);
            }
        });
        transactions.add(cb_t_inventory_adjuster);

        cb_t_purchase_order.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_purchase_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_purchase_order.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_purchase_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_t_purchase_order.setText("PURCHASE ORDER");
        cb_t_purchase_order.setOpaque(true);
        cb_t_purchase_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_purchase_orderActionPerformed(evt);
            }
        });
        transactions.add(cb_t_purchase_order);

        cb_t_voider.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_voider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_voider.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_voider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_drop.png"))); // NOI18N
        cb_t_voider.setText("VOIDER");
        cb_t_voider.setOpaque(true);
        cb_t_voider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_voiderActionPerformed(evt);
            }
        });
        transactions.add(cb_t_voider);

        cb_t_ar.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_ar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_ar.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_ar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_t_ar.setText("ACCOUNTS RECEIVABLE");
        cb_t_ar.setOpaque(true);
        cb_t_ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_arActionPerformed(evt);
            }
        });
        transactions.add(cb_t_ar);

        cb_t_ar_encoding.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_ar_encoding.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_ar_encoding.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_ar_encoding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_t_ar_encoding.setText("ACCOUNTS RECEIVABLE ENCODING");
        cb_t_ar_encoding.setOpaque(true);
        cb_t_ar_encoding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_ar_encodingActionPerformed(evt);
            }
        });
        transactions.add(cb_t_ar_encoding);

        cb_t_ap.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_ap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_ap.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_ap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/branch.png"))); // NOI18N
        cb_t_ap.setText("ACCOUNTS PAYABLE");
        cb_t_ap.setOpaque(true);
        cb_t_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_apActionPerformed(evt);
            }
        });
        transactions.add(cb_t_ap);

        cb_t_services.setBackground(new java.awt.Color(51, 153, 255));
        cb_t_services.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_t_services.setForeground(new java.awt.Color(255, 255, 255));
        cb_t_services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/branch.png"))); // NOI18N
        cb_t_services.setText("Services");
        cb_t_services.setOpaque(true);
        cb_t_services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_t_servicesActionPerformed(evt);
            }
        });
        transactions.add(cb_t_services);

        jPopupMenu1.add(transactions);

        maintenance.setBackground(new java.awt.Color(51, 153, 255));
        maintenance.setForeground(new java.awt.Color(255, 255, 255));
        maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/security_manager.png"))); // NOI18N
        maintenance.setText("MAINTENANCE");
        maintenance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        maintenance.setOpaque(true);

        cb_m_items.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/items.png"))); // NOI18N
        cb_m_items.setText("ITEM");
        cb_m_items.setOpaque(true);
        cb_m_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_itemsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_items);

        cb_m_category.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_category.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/category.png"))); // NOI18N
        cb_m_category.setText("CATEGORY");
        cb_m_category.setOpaque(true);
        cb_m_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_categoryActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_category);

        cb_m_users.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_users.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_users.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/users.png"))); // NOI18N
        cb_m_users.setText("USERS");
        cb_m_users.setOpaque(true);
        cb_m_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_usersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_users);

        cb_m_uom.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_uom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_uom.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_uom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/uom.png"))); // NOI18N
        cb_m_uom.setText("UNIT OF MEASURE");
        cb_m_uom.setOpaque(true);
        cb_m_uom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_uomActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_uom);

        cb_m_supplier.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_supplier.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/suppliers.png"))); // NOI18N
        cb_m_supplier.setText("SUPPLIER");
        cb_m_supplier.setOpaque(true);
        cb_m_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_supplierActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_supplier);

        cb_m_customers.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_customers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_customers.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer.png"))); // NOI18N
        cb_m_customers.setText("CUSTOMERS");
        cb_m_customers.setOpaque(true);
        cb_m_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_customersActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_customers);

        cb_m_discounts.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_discounts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_discounts.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_discounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/customer_item_pricing.png"))); // NOI18N
        cb_m_discounts.setText("DISCOUNTS");
        cb_m_discounts.setOpaque(true);
        cb_m_discounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_discountsActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_discounts);

        cb_m_banks.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_banks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_banks.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_banks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_b.png"))); // NOI18N
        cb_m_banks.setText("BANKS");
        cb_m_banks.setOpaque(true);
        cb_m_banks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_banksActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_banks);

        cb_m_services.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_services.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_services.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/master_file.png"))); // NOI18N
        cb_m_services.setText("SERVICES");
        cb_m_services.setOpaque(true);
        cb_m_services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_servicesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_services);

        cb_m_expenses.setBackground(new java.awt.Color(51, 153, 255));
        cb_m_expenses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_m_expenses.setForeground(new java.awt.Color(255, 255, 255));
        cb_m_expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_m_expenses.setText("EXPENSES");
        cb_m_expenses.setOpaque(true);
        cb_m_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_m_expensesActionPerformed(evt);
            }
        });
        maintenance.add(cb_m_expenses);

        jPopupMenu1.add(maintenance);

        reports.setBackground(new java.awt.Color(51, 153, 255));
        reports.setForeground(new java.awt.Color(255, 255, 255));
        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        reports.setText("REPORTS");
        reports.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reports.setOpaque(true);

        cb_r_encoding_inventory.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_encoding_inventory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_encoding_inventory.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_encoding_inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_encoding_inventory.setText("ENCODING INVENTORY");
        cb_r_encoding_inventory.setOpaque(true);
        cb_r_encoding_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_encoding_inventoryActionPerformed(evt);
            }
        });
        reports.add(cb_r_encoding_inventory);

        cb_r_sales.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_sales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_sales.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales.png"))); // NOI18N
        cb_r_sales.setText("SALES REPORT");
        cb_r_sales.setOpaque(true);
        cb_r_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_salesActionPerformed(evt);
            }
        });
        reports.add(cb_r_sales);

        cb_r_sales_items.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_sales_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_sales_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_sales_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_ledger.png"))); // NOI18N
        cb_r_sales_items.setText("SALES ITEMS");
        cb_r_sales_items.setOpaque(true);
        cb_r_sales_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_sales_itemsActionPerformed(evt);
            }
        });
        reports.add(cb_r_sales_items);

        cb_r_cash_count.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_cash_count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_cash_count.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_cash_count.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_b.png"))); // NOI18N
        cb_r_cash_count.setText("CASH COUNT");
        cb_r_cash_count.setOpaque(true);
        cb_r_cash_count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_cash_countActionPerformed(evt);
            }
        });
        reports.add(cb_r_cash_count);

        cb_r_receipts.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_receipts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_receipts.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_receipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/receipts.png"))); // NOI18N
        cb_r_receipts.setText("RECEIPTS");
        cb_r_receipts.setOpaque(true);
        cb_r_receipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_receiptsActionPerformed(evt);
            }
        });
        reports.add(cb_r_receipts);

        cb_r_stock_transferred.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stock_transferred.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stock_transferred.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stock_transferred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/orders_and_deliveries.png"))); // NOI18N
        cb_r_stock_transferred.setText("STOCK TRANSFER");
        cb_r_stock_transferred.setOpaque(true);
        cb_r_stock_transferred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stock_transferredActionPerformed(evt);
            }
        });
        reports.add(cb_r_stock_transferred);

        cb_r_stocks_left_category.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stocks_left_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stocks_left_category.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stocks_left_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stocks_left_category.setText("STOCKS LEFT by Category");
        cb_r_stocks_left_category.setOpaque(true);
        cb_r_stocks_left_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stocks_left_categoryActionPerformed(evt);
            }
        });
        reports.add(cb_r_stocks_left_category);

        cb_r_stocks_left_supplier.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stocks_left_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stocks_left_supplier.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stocks_left_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stocks_left_supplier.setText("STOCKS LEFT by Supplier");
        cb_r_stocks_left_supplier.setOpaque(true);
        cb_r_stocks_left_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stocks_left_supplierActionPerformed(evt);
            }
        });
        reports.add(cb_r_stocks_left_supplier);

        cb_r_items.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_items.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_items.setText("ITEMS by Category");
        cb_r_items.setOpaque(true);
        cb_r_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_itemsActionPerformed(evt);
            }
        });
        reports.add(cb_r_items);

        cb_r_purchase_order.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_purchase_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_purchase_order.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_purchase_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/item_references.png"))); // NOI18N
        cb_r_purchase_order.setText("PURCHASE ORDER");
        cb_r_purchase_order.setOpaque(true);
        cb_r_purchase_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_purchase_orderActionPerformed(evt);
            }
        });
        reports.add(cb_r_purchase_order);

        cb_r_voider.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_voider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_voider.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_voider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/b_drop.png"))); // NOI18N
        cb_r_voider.setText("VOIDER");
        cb_r_voider.setOpaque(true);
        cb_r_voider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_voiderActionPerformed(evt);
            }
        });
        reports.add(cb_r_voider);

        cb_r_stock_status.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stock_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stock_status.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stock_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stock_status.setText("STOCK STATUS");
        cb_r_stock_status.setOpaque(true);
        cb_r_stock_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stock_statusActionPerformed(evt);
            }
        });
        reports.add(cb_r_stock_status);

        cb_r_stock_ledger.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_stock_ledger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_stock_ledger.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_stock_ledger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/reference_code.png"))); // NOI18N
        cb_r_stock_ledger.setText("STOCK LEDGER");
        cb_r_stock_ledger.setOpaque(true);
        cb_r_stock_ledger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_stock_ledgerActionPerformed(evt);
            }
        });
        reports.add(cb_r_stock_ledger);

        cb_r_customers.setBackground(new java.awt.Color(51, 153, 255));
        cb_r_customers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_r_customers.setForeground(new java.awt.Color(255, 255, 255));
        cb_r_customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/customer2.png"))); // NOI18N
        cb_r_customers.setText("CUSTOMERS");
        cb_r_customers.setOpaque(true);
        cb_r_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r_customersActionPerformed(evt);
            }
        });
        reports.add(cb_r_customers);

        jPopupMenu1.add(reports);

        bir.setBackground(new java.awt.Color(51, 153, 255));
        bir.setForeground(new java.awt.Color(255, 255, 255));
        bir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/reports.PNG"))); // NOI18N
        bir.setText("BIR");
        bir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bir.setOpaque(true);

        cb_b_x_reading.setBackground(new java.awt.Color(51, 153, 255));
        cb_b_x_reading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_x_reading.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_x_reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_registry.png"))); // NOI18N
        cb_b_x_reading.setText("X Reading");
        cb_b_x_reading.setOpaque(true);
        cb_b_x_reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_x_readingActionPerformed(evt);
            }
        });
        bir.add(cb_b_x_reading);

        cb_b_z_reading.setBackground(new java.awt.Color(51, 153, 255));
        cb_b_z_reading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_z_reading.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_z_reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/sales_ledger.png"))); // NOI18N
        cb_b_z_reading.setText("Z Reading");
        cb_b_z_reading.setOpaque(true);
        cb_b_z_reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_z_readingActionPerformed(evt);
            }
        });
        bir.add(cb_b_z_reading);

        cb_b_reading_trails.setBackground(new java.awt.Color(51, 153, 255));
        cb_b_reading_trails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_b_reading_trails.setForeground(new java.awt.Color(255, 255, 255));
        cb_b_reading_trails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/stock_status.png"))); // NOI18N
        cb_b_reading_trails.setText("X Reading");
        cb_b_reading_trails.setActionCommand("READING TRAILS");
        cb_b_reading_trails.setOpaque(true);
        cb_b_reading_trails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_b_reading_trailsActionPerformed(evt);
            }
        });
        bir.add(cb_b_reading_trails);

        jPopupMenu1.add(bir);

        help.setBackground(new java.awt.Color(51, 153, 255));
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/help.png"))); // NOI18N
        help.setText("HELP");
        help.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        help.setOpaque(true);
        jPopupMenu1.add(help);

        stand_by.setBackground(new java.awt.Color(51, 153, 255));
        stand_by.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stand_by.setForeground(new java.awt.Color(255, 255, 255));
        stand_by.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/maintenance.png"))); // NOI18N
        stand_by.setText("STAND BY");
        stand_by.setOpaque(true);
        stand_by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stand_byActionPerformed(evt);
            }
        });
        jPopupMenu1.add(stand_by);

        LOGOUT.setBackground(new java.awt.Color(51, 153, 255));
        LOGOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img/s_reload.png"))); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.setOpaque(true);
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jPopupMenu1.add(LOGOUT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(16, 88, 197));

        jLabel51.setBackground(new java.awt.Color(234, 234, 234));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Retail/pnl/menu53.png"))); // NOI18N
        jLabel51.setOpaque(true);
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("V2.0.1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(16, 88, 197));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img_menu/FOLDER - DOCUMENTS_32x32-32.png"))); // NOI18N
        jLabel7.setText("Algorithm");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        pnl_main_holder.setBackground(new java.awt.Color(204, 204, 204));
        pnl_main_holder.setLayout(new java.awt.CardLayout());

        pnl_login.setBackground(new java.awt.Color(255, 255, 255));

        login.setOpaque(false);

        jLabel8.setBackground(new java.awt.Color(16, 88, 197));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(16, 88, 197));
        jLabel8.setText("Username:");

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(16, 88, 197));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(16, 88, 197));
        jLabel12.setText("Password:");

        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(16, 88, 197));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(16, 88, 197));
        jLabel13.setText("Login with your ");

        jLabel14.setBackground(new java.awt.Color(16, 88, 197));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(16, 88, 197));
        jLabel14.setText("credentials!");

        jButton1.setText("Run Script");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_username)
                    .addComponent(tf_password)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_main_holder.add(pnl_login, "card5");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_main_holder.add(jPanel1, "card2");

        jPanel6.setBackground(new java.awt.Color(227, 221, 221));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_main_holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_main_holder, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_m_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_categoryActionPerformed

    }//GEN-LAST:event_cb_m_categoryActionPerformed

    private void cb_m_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_usersActionPerformed

    }//GEN-LAST:event_cb_m_usersActionPerformed

    private void cb_m_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_itemsActionPerformed

    }//GEN-LAST:event_cb_m_itemsActionPerformed

    private void cb_t_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_salesActionPerformed

    }//GEN-LAST:event_cb_t_salesActionPerformed

    private void cb_r_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_salesActionPerformed

    }//GEN-LAST:event_cb_r_salesActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed

    }//GEN-LAST:event_LOGOUTActionPerformed

    private void cb_t_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_receiptsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_t_receiptsActionPerformed

    private void cb_t_stock_tranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_stock_tranferActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_t_stock_tranferActionPerformed

    private void cb_m_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_supplierActionPerformed

    }//GEN-LAST:event_cb_m_supplierActionPerformed

    private void cb_r_cash_countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_cash_countActionPerformed

    }//GEN-LAST:event_cb_r_cash_countActionPerformed

    private void cb_r_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_receiptsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_r_receiptsActionPerformed

    private void cb_r_stock_transferredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stock_transferredActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_r_stock_transferredActionPerformed

    private void cb_r_stocks_left_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stocks_left_categoryActionPerformed

    }//GEN-LAST:event_cb_r_stocks_left_categoryActionPerformed

    private void stand_byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stand_byActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_stand_byActionPerformed

    private void cb_r_sales_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_sales_itemsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_r_sales_itemsActionPerformed

    private void cb_m_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_customersActionPerformed

    }//GEN-LAST:event_cb_m_customersActionPerformed

    private void cb_m_discountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_discountsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_m_discountsActionPerformed

    private void cb_m_uomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_uomActionPerformed

    }//GEN-LAST:event_cb_m_uomActionPerformed

    private void cb_m_banksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_banksActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_m_banksActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void cb_r_stocks_left_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stocks_left_supplierActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_r_stocks_left_supplierActionPerformed

    private void cb_r_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_itemsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_r_itemsActionPerformed

    private void cb_t_inventory_adjusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_inventory_adjusterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_t_inventory_adjusterActionPerformed

    private void cb_b_x_readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_x_readingActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_b_x_readingActionPerformed

    private void cb_m_servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_servicesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_m_servicesActionPerformed

    private void cb_m_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_m_expensesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_m_expensesActionPerformed

    private void cb_t_purchase_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_purchase_orderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_t_purchase_orderActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_transactionsActionPerformed

    private void cb_b_z_readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_z_readingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_b_z_readingActionPerformed

    private void cb_b_reading_trailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_b_reading_trailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_b_reading_trailsActionPerformed

    private void cb_r_purchase_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_purchase_orderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_r_purchase_orderActionPerformed

    private void cb_t_voiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_voiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_t_voiderActionPerformed

    private void cb_r_voiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_voiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_r_voiderActionPerformed

    private void cb_t_salesmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_salesmanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_t_salesmanActionPerformed

    private void cb_t_arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_arActionPerformed

    }//GEN-LAST:event_cb_t_arActionPerformed

    private void cb_t_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_apActionPerformed

    }//GEN-LAST:event_cb_t_apActionPerformed

    private void cb_t_ar_encodingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_ar_encodingActionPerformed

    }//GEN-LAST:event_cb_t_ar_encodingActionPerformed

    private void cb_t_finalize_receiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_finalize_receiptsActionPerformed

    }//GEN-LAST:event_cb_t_finalize_receiptsActionPerformed

    private void cb_r_stock_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stock_statusActionPerformed

    }//GEN-LAST:event_cb_r_stock_statusActionPerformed

    private void cb_r_stock_ledgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_stock_ledgerActionPerformed

    }//GEN-LAST:event_cb_r_stock_ledgerActionPerformed

    private void cb_t_encode_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_encode_inventoryActionPerformed

    }//GEN-LAST:event_cb_t_encode_inventoryActionPerformed

    private void cb_r_encoding_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_encoding_inventoryActionPerformed

    }//GEN-LAST:event_cb_r_encoding_inventoryActionPerformed

    private void cb_t_finalize_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_finalize_inventoryActionPerformed

    }//GEN-LAST:event_cb_t_finalize_inventoryActionPerformed

    private void cb_r_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r_customersActionPerformed

    }//GEN-LAST:event_cb_r_customersActionPerformed

    private void cb_t_servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_t_servicesActionPerformed

    }//GEN-LAST:event_cb_t_servicesActionPerformed

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        check_credentials();
       
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        check_credentials();
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        menu();
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        check_credentials();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Application.setSystemLookAndFeel();
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Dashboard aw = new Dashboard();
                String url = "/POS/img/5.png";
                Toolkit tk = Toolkit.getDefaultToolkit();
                int xSize = ((int) tk.getScreenSize().
                        getWidth());
                int ySize = ((int) tk.getScreenSize().
                        getHeight());
                aw.setSize(xSize, ySize);
                Dimension d = aw.jPanel1.getSize();
                aw.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LOGOUT;
    private javax.swing.JMenu bir;
    private javax.swing.JMenuItem cb_b_reading_trails;
    private javax.swing.JMenuItem cb_b_x_reading;
    private javax.swing.JMenuItem cb_b_z_reading;
    private javax.swing.JMenuItem cb_m_banks;
    private javax.swing.JMenuItem cb_m_category;
    private javax.swing.JMenuItem cb_m_customers;
    private javax.swing.JMenuItem cb_m_discounts;
    private javax.swing.JMenuItem cb_m_expenses;
    private javax.swing.JMenuItem cb_m_items;
    private javax.swing.JMenuItem cb_m_services;
    private javax.swing.JMenuItem cb_m_supplier;
    private javax.swing.JMenuItem cb_m_uom;
    private javax.swing.JMenuItem cb_m_users;
    private javax.swing.JMenuItem cb_r_cash_count;
    private javax.swing.JMenuItem cb_r_customers;
    private javax.swing.JMenuItem cb_r_encoding_inventory;
    private javax.swing.JMenuItem cb_r_items;
    private javax.swing.JMenuItem cb_r_purchase_order;
    private javax.swing.JMenuItem cb_r_receipts;
    private javax.swing.JMenuItem cb_r_sales;
    private javax.swing.JMenuItem cb_r_sales_items;
    private javax.swing.JMenuItem cb_r_stock_ledger;
    private javax.swing.JMenuItem cb_r_stock_status;
    private javax.swing.JMenuItem cb_r_stock_transferred;
    private javax.swing.JMenuItem cb_r_stocks_left_category;
    private javax.swing.JMenuItem cb_r_stocks_left_supplier;
    private javax.swing.JMenuItem cb_r_voider;
    private javax.swing.JMenuItem cb_t_ap;
    private javax.swing.JMenuItem cb_t_ar;
    private javax.swing.JMenuItem cb_t_ar_encoding;
    private javax.swing.JMenuItem cb_t_encode_inventory;
    private javax.swing.JMenuItem cb_t_finalize_inventory;
    private javax.swing.JMenuItem cb_t_finalize_receipts;
    private javax.swing.JMenuItem cb_t_inventory_adjuster;
    private javax.swing.JMenuItem cb_t_purchase_order;
    private javax.swing.JMenuItem cb_t_receipts;
    private javax.swing.JMenuItem cb_t_sales;
    private javax.swing.JMenuItem cb_t_salesman;
    private javax.swing.JMenuItem cb_t_services;
    private javax.swing.JMenuItem cb_t_stock_tranfer;
    private javax.swing.JMenuItem cb_t_voider;
    private javax.swing.JMenu help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JDesktopPane jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel login;
    private javax.swing.JMenu maintenance;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_main_holder;
    private javax.swing.JMenu reports;
    private javax.swing.JMenuItem stand_by;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    private javax.swing.JMenu transactions;
    // End of variables declaration//GEN-END:variables

    private void myInit() {

        jButton1.setVisible(false);
        jPanel6.setVisible(false);

        String business_name = System.getProperty("business_name", "SYNAPSE SOFTWARE TECHNOLOGY");
        jLabel7.setText(business_name);
        String slogan = System.getProperty("slogan", "INTEGRATING BUSINESS THROUGH TECHNOLOGY");
        time();
        focus();
        set_card_items();

    }

    String my_branch = "";
    String my_branch_id = "";
    String my_location = "";
    String my_location_id = "";

    private void focus() {
        JTextField[] tf = {};
        Focus_Fire.onFocus_lostFocus(tf);
    }
    CardLayout cardLayout = new CardLayout();

    private void set_card_items() {
        cardLayout = (CardLayout) pnl_main_holder.getLayout();
        cardLayout.addLayoutComponent("1", pnl_login);
        cardLayout.addLayoutComponent("2", jPanel1);
    }

    private void time() {
    }

    public JDesktopPane pane() {
        return jPanel1;
    }

    public void login() {
        Window p = (Window) this;
        Dlg_login nd = Dlg_login.create(p, true);
        nd.setTitle("");
        nd.setCallback(new Dlg_login.Callback() {
            @Override
            public void ok(CloseDialog closeDialog, Dlg_login.OutputData data) {
                closeDialog.ok();
                jPanel1.removeAll();
                jPanel1.updateUI();
                set_account();
            }
        });
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().
                getWidth());

        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - nd.getWidth()) / 2;
        final int y = (screenSize.height - nd.getHeight()) / 2;
        nd.setLocation(0, y);
        nd.setSize(xSize, 50);
        nd.setVisible(true);

    }

    private void set_account() {

    }

    private void hover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(230, 227, 227));
        lbl.setForeground(new java.awt.Color(0, 0, 0));
    }

    private void exit(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(139, 125, 107));
        lbl.setForeground(new java.awt.Color(255, 255, 255));
    }

    private void hover2(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(29, 141, 253));
    }

    private void exit2(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(51, 153, 255));

    }

    private void menu() {

        Window p = (Window) this;
        Dlg_menu nd = Dlg_menu.create(p, true);
        nd.setTitle("");
        nd.setCallback(new Dlg_menu.Callback() {

            @Override
            public void minimize(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();
                Dashboard.this.setState(Frame.ICONIFIED);
            }

            @Override
            public void ok1(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();

                if (data.stmt.equals("standby")) {
                    cardLayout.show(pnl_main_holder, "1");
                }

                if (data.stmt.equals("logout")) {
                    System.exit(1);
                }
                if (data.stmt.equals("minimize")) {
                    Dashboard.this.setState(Frame.ICONIFIED);
                }

                //<editor-fold defaultstate="collapsed" desc=" transactions ">
                //</editor-fold>
                //<editor-fold defaultstate="collapsed" desc=" maintenance ">
                //</editor-fold>
                //<editor-fold defaultstate="collapsed" desc=" Reports ">
                //</editor-fold>
                
            }
            
            @Override
            public void standby(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();
            }
            
            @Override
            public void logout(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();
            }
        });
        Point point = jLabel51.getLocationOnScreen();
        nd.setLocation(point.x - 125, point.y + 37);
        nd.setVisible(true);
    }

    private void check_credentials() {
        String user_name = tf_username.getText();
        String date = DateType.sf.format(new Date());
        String password = tf_password.getText();
        String where = " where user_name ='" + user_name + "' and password='" + password + "' ";
        final Users.to_users to = Users.ret_data_autho(where);
        if (to == null) {
            tf_username.setText("");
            tf_password.setText("");
            tf_username.grabFocus();
            Alert.set(0, "Wrong Username/Password!!");
        } else {

            tf_username.setText("");
            tf_password.setText("");
            Users.setUser_name(user_name);
            Users.setScreen_name(Users.screen_name);
            Users.setPassword("" + to.id);
            MyUser.user_id = "" + to.id;
            MyUser.user_name = Users.user_name;
            MyUser.user_screen_name = Users.screen_name;
            jPanel1.removeAll();
            jPanel1.updateUI();
            set_previleges();
            cardLayout.show(pnl_main_holder, "2");
        }
    }
       
    //<editor-fold defaultstate="collapsed" desc=" privileges ">
    private void set_previleges() {
        String where = " where user_id='" + MyUser.getUser_id() + "' order by previledge asc";
        List<User_previleges.to_user_previleges> datas = User_previleges.ret_data(where);
        for (User_previleges.to_user_previleges to : datas) {
            if (to.previledge.equalsIgnoreCase("Sales")) {
//                cashin();
            }
        }
    }
    //</editor-fold>
}
